In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [1]:
import numpy as np

In [13]:
#Q1
#creating arrays
arr1 =  np.array([1,2,3,4,5,6,7,8,9,10])
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
#reshaping to 2*5 matrix
res_arr1 = arr1.reshape(2,5)
print(res_arr1)
print('Dimension of res_arr1:', res_arr1.ndim)
print('Shape of res_arr1:', res_arr1.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Dimension of res_arr1: 2
Shape of res_arr1: (2, 5)


In [15]:
#Q2
arr = np.arange(1, 21)
arr
extracted_elements = arr[5:16]
print("Extracted elements:", extracted_elements)

Extracted elements: [ 6  7  8  9 10 11 12 13 14 15 16]


In [19]:
#Q3
import pandas as pd

fruit_series = pd.Series({'apples': 3, 'bananas': 2, 'oranges': 1})
fruit_series.loc['pears'] = 4
print(fruit_series)

apples     3
bananas    2
oranges    1
pears      4
dtype: int64


In [23]:
#Q4
# Define the data
data = {
    'name': ['Alice', 'Bob', 'Charlie', 'Das', 'Anu', 'Anandu', 'Priya', 'Prakash', 'Manu', 'Sam'],
    'age': [23, 35, 45, 28, 34, 50, 29, 40, 22, 31],
    'gender': ['F', 'M', 'M', 'M', 'F', 'M', 'F', 'M', 'M', 'M']
}
df = pd.DataFrame(data)
print(df)


      name  age gender
0    Alice   23      F
1      Bob   35      M
2  Charlie   45      M
3      Das   28      M
4      Anu   34      F
5   Anandu   50      M
6    Priya   29      F
7  Prakash   40      M
8     Manu   22      M
9      Sam   31      M


In [27]:
#Q5
# Adding a new row
# use loc
df.loc[:, 'occupation'] = ['Programmer', 'Manager', 'Analyst', 'Programmer', 'Manager', 'Analyst', 'Programmer', 'Manager', 'Analyst', 'Programmer']
df

name  age gender  occupation
0    Alice   23      F  Programmer
1      Bob   35      M     Manager
2  Charlie   45      M     Analyst
3      Das   28      M  Programmer
4      Anu   34      F     Manager
5   Anandu   50      M     Analyst
6    Priya   29      F  Programmer
7  Prakash   40      M     Manager
8     Manu   22      M     Analyst
9      Sam   31      M  Programmer

In [29]:
#Q6
# Select rows where age is greater than or equal to 30
df1 = df[df['age'] >= 30]
print(df1)

      name  age gender  occupation
1      Bob   35      M     Manager
2  Charlie   45      M     Analyst
4      Anu   34      F     Manager
5   Anandu   50      M     Analyst
7  Prakash   40      M     Manager
9      Sam   31      M  Programmer


In [31]:
#Q7
#  Convert DataFrame to CSV
df.to_csv('people_data.csv', index=False)
new_df = pd.read_csv('people_data.csv')
print(new_df)

      name  age gender  occupation
0    Alice   23      F  Programmer
1      Bob   35      M     Manager
2  Charlie   45      M     Analyst
3      Das   28      M  Programmer
4      Anu   34      F     Manager
5   Anandu   50      M     Analyst
6    Priya   29      F  Programmer
7  Prakash   40      M     Manager
8     Manu   22      M     Analyst
9      Sam   31      M  Programmer
